function m(b,a,c,d,e){b.j.pb(b.tb,a,c,d,e)}function n(b,a,c,d){b.j.ba?m(b,a,c,d):b.j.Ye()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.j.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Xb||(b.j.Fc(b.oe),b.Xb=!0)}function aa(b){b.Xb&&(b.j.Md(b.oe),b.Xb=!1)}window.jb=class{constructor(b,a){this.j=b;this.tb=a;this.Xb=!1;this.oe=()=>this.Ga()}ud(){}Ga(){}};
window.Kf=class{constructor(){this.pd=-1}l(){-1!==this.pd&&(self.clearTimeout(this.pd),this.pd=-1)}};"use strict";class ba{constructor(b){this.Va=b;this.Vc=!1;this.cd=!0;this.xb=this.ra=this.qd=-1}}
function da(b,a){const c=a.elementId,d=b.yd(c,a),e=new ba(d);b.xa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.cd=!!a.isVisible;d.addEventListener("focus",()=>{x(b,"elem-focused",c)});d.addEventListener("blur",()=>{x(b,"elem-blurred",c)});const f=a.htmlIndex;e.qd=f;e.xb=a.htmlZIndex;b.Ja&&(a=b.j.vc(f),e.ra=a,b.j.Nb(a).appendChild(d))}function y(b,a,c){q(b,a,d=>{const e=z(b,d.elementId);return c(e,d)})}
function z(b,a){b=b.xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Va}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.uc=class extends self.jb{constructor(b){super(b,"video");this.xa=new Map;this.Ja=!0;v(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=z(this,a);this.Ad(c);this.Ja&&c.parentElement.removeChild(c);this.xa.delete(a)}],["set-visible",a=>{if(this.Ja){var c=this.xa.get(a.elementId),d=c.Va;c.Vc?d.style.display=a.isVisible?"":"none":c.cd=!!a.isVisible}}],["update-position",a=>{if(this.Ja){var c=this.xa.get(a.elementId),d=c.Va,e=this.j;d.style.left=a.left+"px";d.style.top=a.top+
"px";d.style.width=a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.qd=f;f=e.vc(f);f!==c.ra&&(d.remove(),e.Nb(f).appendChild(d),c.ra=f,e.Oc());a=a.htmlZIndex;a!==c.xb&&(c.xb=a,e.Oc());c.Vc||(c.Vc=!0,c.cd&&(d.style.display=""))}}],["update-state",a=>{z(this,a.elementId);this.Fd()}],["focus",a=>{const c=z(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=z(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,
a):c.style[d]=a}],["set-attribute",a=>{z(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{z(this,a.elementId).removeAttribute(a.name)}]]);y(this,"get-element",a=>a)}yd(){throw Error("required override");}Ad(){}Fd(){throw Error("required override");}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),A=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ha=0;function B(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Af?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.Ef+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ia(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let C=new Audio;
const ja={"audio/webm; codecs=opus":!!C.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!C.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!C.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!C.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!C.canPlayType("audio/mp4"),"audio/mpeg":!!C.canPlayType("audio/mpeg")};C=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const E=[];let F=0;window.RealFile=window.File;const H=[],ma=new Map,na=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.Qa=class b{constructor(a){this.ba=a.Gf;this.Aa=null;this.aa="";this.cb=a.Df;this.Lb={};this.Xa=this.wa=null;this.Ua=[];this.oa=null;this.be=!0;this.M=[];this.jd=[];this.kd=!1;this.pe=()=>this.We();this.Zc=!1;this.Wd=0;this.zb=null;this.bb=-1;this.vf=()=>this.gf();this.Ib=new Set;this.rd=null;this.qe=[];this.A=a.re;this.Yb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;fa&&(this.ba=!1);if("cordova"===this.A&&this.ba&&A){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Pa()?self.chrome.webview.addEventListener("message",c=>this.Ld(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Ld(c));this.ac=this.ta=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.lf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.bf());this.B("runtime","cordova-fetch-local-file",c=>this.cf(c));this.B("runtime","create-job-worker",()=>this.df());this.B("runtime","send-wrapper-extension-message",c=>this.kf(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Jd(a)):this.Jd(a)}l(){this.Gc();this.Aa&&(this.Aa=this.Aa.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Xa&&(this.Xa.l(),this.Xa=null);for(const {canvas:a,
gb:c}of this.M)a.remove(),c.remove();this.M.length=0}Bd(){return this.M[0].canvas}vc(a){return Math.min(a,this.M.length-1)}Nb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].gb}Me(){return ea&&"cordova"===this.A}nb(){const a=navigator.userAgent;return ea&&ta.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ke(){return A}Bc(){return A&&ta.has(this.A)}Dd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Pa(){return this.Dd()||"xbox-uwp-webview2"===this.A}async Jd(a){this.ba&&!await ia()&&(this.ba=!1);"macos-wkwebview"===this.A?this.qb({type:"ready"}):this.Pa()&&(this.nf(),this.qe=(await this.af()).registeredComponentIds);if("playable-ad"===this.A){this.ta=self.c3_base64files;this.ac={};await this.Te();for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.ac.hasOwnProperty(c)?a.fb[d]={Af:!0,Ef:this.ac[c]}:this.ta.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.ta[c]))}a.rc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Fc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Cf?this.aa=a.Cf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.If&&(this.Lb=a.If);c=new MessageChannel;this.Aa=c.port1;this.Aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.ff(d));this.zb=
new self.Ne(this);await va(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.$e(a,c.port2):await this.Ze(a,c.port2)}Ic(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.A&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async tc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Yb)return a=await this.Mb(d.zf?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}xc(){return this.Pa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Id(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ia(),g=this.xc(),
h=window.devicePixelRatio,k=b.mb(),l=a.Nf,p=window.cr_previewImageBlobs||this.ta,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.re;var ca=(new URLSearchParams(self.location.search)).has("debug"),G=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:ca,
ife:!!self.Mf,jobScheduler:{inputPort:G.Yc,outputPort:G.hd,maxNumWorkers:G.sf},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cb+"opus.wasm.wasm",isFileProtocol:this.Yb,isiOSCordova:this.Me(),isiOSWebView:this.nb(),isWindowsWebView2:this.Dd(),isAnyWebView2Wrapper:this.Pa(),wrapperComponentIds:this.qe,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async $e(a,c){const d=this.Ic(a.Hf);"preview"===
this.A?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.tc(d,this.aa,{type:"module",name:"Runtime",zf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,gb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.rc||[],k=a.fb;h=await Promise.all(h.map(l=>this.Ra(l)));k=await Promise.all(k.map(l=>this.Ra(l)));if("cordova"===this.A)for(let l=0,p=a.qc.length;l<p;++l){const r=a.qc[l],t=r[0];if(t===a.sd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ra(t)}this.wa.postMessage(Object.assign(this.Id(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.qc,mainProjectScript:a.sd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...wa(this.zb)]);this.Ua=H.map(l=>new l(this));this.Hd();xa(e);ya(g);za(this.oa);self.c3_callFunction=(l,p)=>{var r=this.oa;return r.j.Ed(r.tb,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Ze(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,gb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ua=H.map(h=>new h(this));this.Hd();xa(d);ya(e);e=a.fb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.rc)){var f=[...a.rc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ra(h)));await Promise.all(e.map(h=>B(h)));e=self.C3_ProjectScriptsStatus;f=a.sd;const g=a.qc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ra(k),await B(k),"preview"!==this.A||e[h]||this.Nd(h,"main script did not run to completion")}catch(l){this.Nd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ra(k),await B(k);"preview"===this.A&&"object"!==typeof self.Jf.Lf?(this.Sb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Id(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:sa}),za(this.oa),this.Kd(),this.Xa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Xa,a))}Nd(a,c){this.Sb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Kd(){this.Sb()}Sb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async df(){const a=await Aa(this.zb);return{outputPort:a,transferables:[a]}}lf(a){if(!this.Zc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,gb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.be&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.be=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,gb:p}=this.M.pop();p.remove();this.ba&&!d?this.jd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,xa(c),ya(d),this.M.push({canvas:c,gb:d});for(const l of this.Ua)if(l instanceof window.uc&&l.Ja)for(const p of l.xa.values())e=l.j.vc(p.qd),f=p.ra,-1!==
e&&-1!==f&&e!==f&&(f=p.Va,f.remove(),l.j.Nb(e).appendChild(f),p.ra=e);this.Oc();return{addedCanvases:a,transferables:k}}bf(){for(const a of this.jd)a.remove();this.jd.length=0}Oc(){this.kd||(this.kd=!0,this.Fc(this.pe))}We(){this.Md(this.pe);this.kd=!1;let a=[];for(var c of this.Ua)if(c instanceof window.uc){var d=c.Ja?[...c.xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Gd(c,a.slice(d,
e)),c=g.ra,d=e)}d<e&&this.Gd(c,a.slice(d,e))}Gd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Va);var d=new Set(c);a=this.Nb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ye(){if(this.ba)throw Error("not available in worker mode");return this.Xa}pb(a,c,d,e,f){this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Ed(a,c,d,e,f){const g=ra++,h=new Promise((k,l)=>{na.set(g,{resolve:k,reject:l})});this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.ef(a);if("result"===c)this.hf(a);else if("runtime-ready"===c)this.jf();else if("alert-error"===c)this.Sb(),alert(a.message);else if("creating-runtime"===c)this.Kd();else throw Error(`unknown message '${c}'`);}ef(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=ma.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Rb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Rb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Rb(f,!1,""+h)}):this.Rb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Rb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Aa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}hf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=na.get(c);d?e.resolve(a):e.reject(a);na.delete(c)}B(a,c,d){let e=ma.get(a);e||(e=new Map,ma.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static hb(a){if(H.includes(a))throw Error("DOM handler already added");H.push(a)}Hd(){for(const a of this.Ua)if("runtime"===a.tb){this.oa=a;return}throw Error("cannot find runtime DOM handler");
}ff(a){this.pb("debugger","message",a)}jf(){for(const a of this.Ua)a.ud()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Od(a){ua=!!a}Fc(a){this.Ib.add(a);this.Nc()}Md(a){this.Ib.delete(a);0===this.Ib.size&&this.Gc()}Nc(){-1===this.bb&&0<this.Ib.size&&(this.bb=requestAnimationFrame(this.vf))}Gc(){-1!==this.bb&&(cancelAnimationFrame(this.bb),this.bb=-1)}gf(){this.bb=-1;for(const a of this.Ib)a();this.Nc()}ca(a){this.oa.ca(a)}ha(a){this.oa.ha(a)}Mc(){this.oa.Mc()}Qb(a){this.oa.Qb(a)}Le(){return!!ja["audio/webm; codecs=opus"]}async pf(a){a=
await this.Ed("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Pe(a){this.Zc=!0;this.Wd=a}Je(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Cd(a){return!this.Je(a)}async Ra(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Yb&&this.Cd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async cf(a){const c=a.filename;switch(a.as){case "text":return await this.Ie(c);
case "buffer":return await this.Mb(c);default:throw Error("unsupported type");}}xd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ie(a){a=await this.xd(a);return await ka(a)}Hc(){if(E.length&&!(8<=F)){F++;var a=E.shift();this.Ue(a.filename,a.Ff,a.yf)}}Mb(a){return new Promise((c,d)=>{E.push({filename:a,Ff:e=>{F--;this.Hc();c(e)},yf:e=>{F--;this.Hc();d(e)}});this.Hc()})}async Ue(a,c,d){try{const e=
await this.xd(a),f=await la(e);c(f)}catch(e){d(e)}}Ld(a){if("entered-fullscreen"===a)b.Od(!0),I(this.oa);else if("exited-fullscreen"===a)b.Od(!1),I(this.oa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.rd(a),this.rd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}kf(a){this.qb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}qb(a){this.Pa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}nf(){window.moveTo=(a,c)=>{this.qb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.qb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}af(){return this.Pa()?new Promise(a=>{this.rd=a;this.qb({type:"wrapper-init"})}):
Promise.resolve()}async Te(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Se(c,d));await Promise.all(a)}async Se(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Xe(c);d||(d=this.Ve(c));this.ta[a]=d}}async Xe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ve(a){a=this.mf(a);return this.Re(a.data,a.Bf)}mf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Bf:a,data:d}}Re(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.Qa,Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ga(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ga(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function xa(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function ya(b){b.addEventListener("selectstart",Ka);b.addEventListener("gesturehold",Ka);b.addEventListener("touchstart",Ka)}function za(b){b.Vd=!0;b.dd=b.j.qa();b.Ab=b.j.ia()}
function I(b){if(!b.ma){var a=J.mb();a&&"any"!==b.nd&&Na(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ia()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Ud=!0},1E3);"cordova"===b.j.A?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.fc=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.fc}}
function Va(b){b.Qd||(b.Qd=!0,window.addEventListener("deviceorientation",a=>{b.ma||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ma||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Wa(b){b.Pd||(b.Pd=!0,window.addEventListener("devicemotion",a=>{if(!b.ma){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Xa(b){await Ea(b.url)}
function Ya(b,a){b.Xd=a.message;-1===b.Tc&&(b.Tc=setTimeout(()=>{b.Tc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Xd)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.qa(),innerHeight:b.ia()})}
function Ua(b,a){b.fc!==a&&((b.fc=a)?b.j.Gc():b.j.Nc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function $a(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.j.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ma){var d=Ba.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.ma||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ma){var d=0;"mouse"===c.pointerType&&(d=b.fd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.fd=c.buttons)}}function ab(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Da=a))}}
function bb(b,a,c,d){const e=b.qa(),f=b.ia();b.eb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:b.j.xc()}):10>d&&cb(b,e,f,d+1)}function cb(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>bb(b,a,c,d),48)}
function Na(b){b=b.nd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.hb(class extends self.jb{constructor(b){super(b,"runtime");this.Vd=!1;this.eb=-1;this.nd="any";this.fc=this.Pd=this.Qd=!1;this.mc=document.createElement("div");this.mc.className="c3-screen-reader-text";this.mc.setAttribute("aria-live","polite");document.body.appendChild(this.mc);this.Ka=null;this.ma=!1;this.Xd="";this.Tc=-1;this.Ud=!1;this.dd=b.qa();this.Ab=b.ia();this.Da=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Oa(c));b.B("runtime","raster-svg-image",c=>Pa(c));b.B("runtime","get-svg-image-size",c=>Ra(c));b.B("runtime","set-target-orientation",c=>{this.nd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Sa(c));b.B("runtime","go-to-script",c=>Sa(c));b.B("runtime","before-start-ticking",()=>Ta(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Va(this));b.B("runtime","enable-device-motion",()=>Wa(this));b.B("runtime","add-stylesheet",c=>Xa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.mc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ma=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.Bd().style.display="";this.j.Pe(c.duration)});b.B("runtime","export-to-video-progress",c=>Ya(this,c));b.B("runtime","exported-to-video",c=>{window.xf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.xf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ha(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.fd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ma&&this.Vd){var c=this.qa();var d=this.ia();if(this.j.Bc()){if(this.Ud){if(this.dd===
c&&d<this.Ab){this.Kb=this.Ab-d;ab(this,this.Ab,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,ab(this,d,this.Kb))}this.dd=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:this.j.xc()});this.j.nb()&&(-1!==this.eb&&clearTimeout(this.eb),bb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Za(this,c));window.addEventListener("webkitfullscreenerror",c=>Za(this,c));window.addEventListener("mozfullscreenerror",c=>Za(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Ya=new Set;this.cc=new WeakSet;this.za=!1}ud(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Da);this.fd=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&m(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
Ca));window.addEventListener("mousemove",a=>M(this,"mousemove",a,Ca));window.addEventListener("mouseup",a=>M(this,"mouseup",a,Ca));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ma||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Da,pageX:a.pageX,pageY:a.pageY+this.Da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
db(a.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.j.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Mc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.j.Ke()&&!this.j.Bc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}));this.j.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ia(){return this.j.ia()}Mc(){var b=
[...this.Ya];this.Ya.clear();if(!this.za)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.Ya.add(a)})}ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.Ya.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.Ya.add(b)})}ha(b){this.Ya.delete(b);this.cc.add(b)}Qb(b){this.za=!!b}});"use strict";
async function va(b){if(b.qf)throw Error("already initialised");b.qf=!0;var a=b.Ba.Ic(("playable-ad"===b.Ba.A?b.Ba.cb:"")+"dispatchworker.js");b.Sc=await b.Ba.tc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Yc=a.port1;b.Sc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.hd=await Aa(b)}function wa(b){return[b.Yc,b.hd]}
async function Aa(b){const a=b.ce.length;var c=b.Ba.Ic(("playable-ad"===b.Ba.A?b.Ba.cb:"")+"jobworker.js");c=await b.Ba.tc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Sc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ce.push(c);return e.port1}
self.Ne=class{constructor(b){this.Ba=b;this.sb=b.aa;this.sb="preview"===b.A?this.sb+"workers/":this.sb+b.cb;this.sf=Math.min(navigator.hardwareConcurrency||2,16);this.Sc=null;this.ce=[];this.hd=this.Yc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Qa({Gf:!0,Hf:"workermain.js",fb:["scripts/c3runtime.js"],qc:[],sd:"",Df:"scripts/",rc:[],re:"html5"}));"use strict";
self.Qa.hb(class extends self.jb{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.Bd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function eb(b,a){a=a.type;let c=!0;0===a?c=await fb():1===a&&(c=await gb());m(b,"permission-result",{type:a,result:c})}async function fb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function gb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Qa.hb(class extends self.jb{constructor(b){super(b,"touch");q(this,"request-permission",a=>eb(this,a))}});"use strict";
async function hb(b,a){b.ad=a.isInWorker;a=document.createElement("video");b.nc=!!a.requestVideoFrameCallback&&!b.j.Bc();const c=!!self.createImageBitmap;b.Hb=b.ad||c;return{postImageBitmaps:b.Hb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function kb(b,a){if(!b.Rc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>kb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function O(b,a,c,d){b.Rc.has(a)||x(b,"playback-event",c,{type:d})}
self.Qa.hb(class extends self.uc{constructor(b){super(b);this.Hb=this.nc=this.ad=this.Ja=!1;this.dc=this.wf=0;this.Rc=new WeakSet;q(this,"init",a=>hb(this,a));y(this,"play",a=>{this.ca(a)});y(this,"pause",a=>{this.ha(a);a.pause()});y(this,"set-source",(a,c)=>{a.src=c.src;a.load()});y(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});y(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});y(this,"set-looping",(a,c)=>{a.loop=c.isLooping});y(this,"set-muted",(a,c)=>{a.muted=c.isMuted});y(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>z(this,a)}ca(b){this.j.ca(b);this.Hb&&this.nc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>kb(this,b)))}ha(b){this.j.ha(b);this.Hb&&this.nc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}yd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>O(this,c,b,0));c.addEventListener("canplaythrough",()=>O(this,c,b,1));c.addEventListener("ended",()=>O(this,c,b,2));c.addEventListener("error",()=>O(this,c,b,3));c.addEventListener("loadstart",()=>O(this,c,b,4));c.addEventListener("playing",()=>O(this,c,b,5));c.addEventListener("pause",()=>O(this,c,b,6));c.addEventListener("stalled",()=>O(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ca(c);this.dc++;w(this);return c}Fd(){}Ad(b){this.ha(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.dc=Math.max(this.dc-1,0);0===this.dc&&aa(this);this.Rc.add(b)}Ga(){const b={},a={sequenceNumber:this.wf++,videoData:b},c=[],d=[];for(const [e,f]of this.xa.entries()){const g=f.Va,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Hb)if(this.nc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.ad?m(this,"state",a,!1,c):n(this,"state",a)})}});"use strict";const lb=180/Math.PI;
async function mb(b,a){if(a.isiOSCordova||a.isSafari)b.ic=!0;b.od=a.timeScaleMode;b.he=["equalpower","HRTF","soundfield"][a.panningModel];b.Td=["linear","inverse","exponential"][a.distanceModel];b.ie=a.refDistance;b.ge=a.maxDistance;b.ke=a.rolloffFactor;if(b.j.Zc)b.ic=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Wd)});else{var c={latencyHint:a.latencyHint};b.ne||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");nb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&nb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.da);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ob(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.de=g.slice(0);pb(b,g);try{b.R=await qb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,ca=p.x,G=p.y,Eb=p.z,Fb=p.angle,oa=p.innerAngle,pa=p.outerAngle,qa=p.outerGain;if(u.yb){rb(u,ca,G,Eb,Fb);var D=self.ib.Qe;
u.ua[0]!==D(oa)&&(u.ua[0]=D(oa),u.F.coneInnerAngle=D(oa));u.ua[1]!==D(pa)&&(u.ua[1]=D(pa),u.F.coneOuterAngle=D(pa));u.ua[2]!==qa&&(u.ua[2]=qa,u.F.coneOuterGain=qa)}p.hasOwnProperty("uid")&&(b.R.sa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),sb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(Gb){console.error("[Construct] Audio: error starting playback: ",Gb);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.td--;0===d.td&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function tb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ub(b,c);for(const h of S(b,c))if(!h.ya){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Na=d;h.Wa=g;h.me=a}T(b)}async function vb(b,a){const c=a.tags;a=a.rate;await ub(b,c);for(const d of S(b,c))d.na!==a&&(d.na=a,d.Ha())}async function wb(b,a){const c=a.tags;a=a.pos;await ub(b,c);for(const d of S(b,c))d.Cc(a)}
async function xb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await qb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function yb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function zb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.xe(b,...e);else if("delay"===c)d=new self.ve(b,...e);else if("convolution"===c){var g=d=new self.ue(b,f.ja,...e),h=a.bufferType;g.Rd=a.bufferOriginalUrl;g.Sd=h}else if("flanger"===c)d=
new self.ye(b,...e);else if("phaser"===c)d=new self.Ae(b,...e);else if("gain"===c)d=new self.ze(b,...e);else if("stereopan"===c)d=new self.Ce(b,...e);else if("tremolo"===c)d=new self.De(b,...e);else if("ringmod"===c)d=new self.Be(b,...e);else if("distortion"===c)d=new self.we(b,...e);else if("compressor"===c)d=new self.te(b,...e);else if("analyser"===c)d=new self.se(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.la.get(h);l||(l=[],g.la.set(h,l));d.ae=l.length;d.md=
h;l.push(d);Ab(g,h)}Bb(b)}
async function Cb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ea()&&1===c||!e.Ea()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.la.values())for(const g of f)g.l();b.la.clear();b.oc=a.timeScale;b.Uc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.da[e]=d[e];b.g.listener.setOrientation(...b.da)}b.za=a.isSilent;b.j.Qb(b.za);b.bc=a.masterVolume;b.Ta.gain.value=
b.bc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>zb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Db(b,f,c)));T(b)}
async function Hb(b,a){try{const c=b.g.suspend(a.time);b.$d?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ib(d)),b.$d=!0);await c}catch(c){Ib(c)}}
function nb(b){b.Wb||(b.Xc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Wb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.lb()===c)return await Jb(g),g;if(f)return null;if(e&&(b.ic||b.Zd)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ea()?g.l():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.ne;e&&f&&(b.Zd=!0);c=!e||b.ic||f?new self.Ge(b,a,c,d,e,f):new self.Ee(b,a,c,d,e);b.ka.push(c);await Jb(c);b.fe.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.fe.add(a));return c}
function Kb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Lb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.fa()}function Ab(b,a){a=a.toLowerCase();let c=b.fa();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Mb(b,a))e=f,d=c,e=e.ea||e.F||e.G,e.disconnect(),e.connect(d);b.La&&b.ed===a&&(b.La.disconnect(),b.La.connect(c))}
function*Mb(b,a){if(a)for(const c of b.H)Kb(0<c.pa.length?c.pa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Nb(b,a,c){return c?b.j.pf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ob(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.pa;var c=a;for(const e of c){c=!1;for(const f of b)if(Kb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function qb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.sc()||f))return g.pa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Pc?new self.Fe(a.u,a,e):new self.He(a.u,a,e);b.H.push(e);return e}
function pb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={td:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.td++}function ub(b,a){return(b=b.Gb.get((0===a.length?b.de:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Sa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Pb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Bb(b){b.$c||(b.$c=!0,Promise.resolve().then(()=>Qb(b)))}
function Qb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.$c=!1}
async function Db(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await qb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],f=d.orient,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],e.setPosition(...b.$a),e.setOrientation(...b.Za),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),sb(b,d));c.Play(k,l,p,0);a.isPlaying||c.ob();c.Kc(a)}}}function Ib(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.jb{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Wb=this.Xc=!1;this.Ca=()=>{if(!this.Xc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Wb&&(this.Xc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Wb=!1)}};this.ka=[];this.H=[];this.R=null;this.de=[];this.fe=new Set;this.ee=-1;this.Gb=new Map;this.bc=1;this.za=!1;this.od=0;this.oc=1;this.Uc=0;this.he="HRTF";this.Td="inverse";this.ie=600;this.ge=1E4;this.ke=1;this.$=[0,0,0];this.da=[0,0,-1,0,1,0];this.Zd=this.ic=!1;this.ne=this.j.Le();this.la=new Map;this.Sa=new Set;this.$d=this.$c=!1;this.ed="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.ed=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Lb(this,this.ed))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Ta.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>mb(this,a)],["play",a=>ob(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Fa()}],["stop-all",()=>{for(const a of this.H)a.Fa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Pb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>tb(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Ta.gain.value=this.bc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Rb(d,a)}],["set-silent",a=>{this.za=a.isSilent;this.j.Qb(this.za);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.Dc(a)}],["set-playback-rate",a=>vb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),sb(d,a)}],["seek",a=>wb(this,a)],["preload",a=>xb(this,a)],["unload",a=>yb(this,a)],["unload-all",()=>{for(const a of this.ka)a.l();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ec(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>zb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Bb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.la.delete(a);Ab(this,a)}}],["tick",a=>{this.oc=a.timeScale;this.Uc=a.gameTime;this.ee=a.tickCount;if(0!==this.od)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.da[0]!==
c[0]||this.da[1]!==c[1]||this.da[2]!==c[2]||this.da[3]!==c[3]||this.da[4]!==c[4]||this.da[5]!==c[5])){for(let d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&rb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Cb(this,a)],["offline-render-audio",a=>Hb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Ob(){return this.za}ca(b){this.j.ca(b)}ha(b){this.j.ha(b)}Ga(){for(var b of this.Sa)b.Ga();
b=this.g.currentTime;for(var a of this.H)a.Ga(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.ee,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.md,index:c.ae,peak:c.ab,rms:c.je,binCount:c.m.frequencyBinCount,freqBins:c.Yd}))});0===a.length&&0===this.Sa.size&&aa(this)}static Qe(b){return b*lb}static zd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Oe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.Qa.hb(self.ib);"use strict";function Jb(b){b.$b||(b.$b=b.Jc());return b.$b}self.vd=class{constructor(b,a,c,d,e){this.u=b;this.uf=a;this.Ma=c;this.T=d;this.rf=e;this.Pc="";this.$b=null}l(){this.$b=this.u=null}Jc(){}V(){return this.u.V()}yc(){return this.uf}lb(){return this.Ma}wc(){return this.T}Ea(){return this.rf}ga(){}};"use strict";
self.Ee=class extends self.vd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Pc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ma}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}l(){Ob(this.u,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Jc(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Ma})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Sb(b){if(b.Ia)return b.Ia;var a=b.u.j;if("cordova"===a.A&&a.Cd(b.Ma)&&a.Yb)b.Ia=await a.Mb(b.Ma);else{a=await fetch(b.Ma);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ia=await a.arrayBuffer()}}async function Tb(b){if(b.ja)return b.ja;b.ja=await Nb(b.u,b.Ia,b.tf);b.Ia=null}
self.Ge=class extends self.vd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Pc="webaudio";this.ja=this.Ia=null;this.tf=!!f}l(){Ob(this.u,this);this.ja=this.Ia=null;super.l()}async Jc(){try{await Sb(this),await Tb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ma}': `,b)}}ga(){return this.ja?this.ja.duration:0}};"use strict";let Ub=0;
function Q(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.he,b.F.distanceModel=b.u.Td,b.F.refDistance=b.u.ie,b.F.maxDistance=b.u.ge,b.F.rolloffFactor=b.u.ke),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function R(b,a){a=!!a;b.Zb!==a&&(b.Zb=a,b.Zb?(Q(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.fa())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.fa())))}function sb(b,a){b.Zb&&b.ld!==a&&(b.ea.pan.value=a,b.ld=a)}function U(b,a){b.Na=a;b.G.gain.cancelScheduledValues(0);b.Wa=-1;b.G.gain.value=b.zc()}function Rb(b,a){a=!!a;b.ya!==a&&(b.ya=a,b.Tb())}
function rb(b,a,c,d,e){if(b.yb){var f=b.$a,g=b.Za,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.bd?b.u.Uc:performance.now()/1E3}
self.wd=class{constructor(b,a,c){this.u=b;this.P=a;this.pa=c;this.Ub=Ub++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.yb=!1;this.$a=[0,0,0];this.Za=[0,0,0];this.ua=[0,0,0];this.ea=null;this.Zb=!1;this.ld=0;this.I=!0;this.Y=this.va=this.J=!1;this.Na=1;this.ya=!1;this.na=1;b=this.u.od;this.bd=1===b&&!this.Ea()||2===b;this.Wa=this.sa=-1;this.me=!1}l(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}fa(){return Lb(this.u,0<this.pa.length?this.pa[0]:"")}yc(){return this.P.yc()}lb(){return this.P.lb()}wc(){return this.P.wc()}Ea(){return this.P.Ea()}O(){}sc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Oa(){}ga(){return this.P.ga()}Play(){}Fa(){}ob(){}Pb(){}Ga(b){-1!==this.Wa&&b>=this.Wa&&(this.Wa=-1,this.me&&this.Fa(),Pb(this.u,"fade-ended",this.pa,this.Ub))}zc(){const b=this.Na;return isFinite(b)?b:0}Ob(){return this.u.Ob()}Tb(){}Dc(){}Ha(){}Cc(){}Ec(){}Ac(){}kb(){var b=
this.Ub,a=this.pa,c=this.ga(),d=-1===this.Wa?this.Na:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.$a,orient:this.Za,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Oa(),playbackRate:this.na,uid:this.sa,bufferOriginalUrl:this.yc(),bufferUrl:"",bufferType:this.wc(),isMusic:this.Ea(),isLooping:this.Y,isMuted:this.ya,resumePosition:this.Ac(),pan:f,stereoPan:this.ea?
this.ld:null}}Kc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ha());Rb(this,b.isMuted)}};"use strict";
self.Fe=class extends self.wd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Lc()}l(){this.Fa();this.P.Fb.disconnect();super.l()}W(){return this.P.W()}Lc(){this.I=!0;this.sa=-1;Pb(this.u,"ended",this.pa,this.Ub)}O(){return this.W().ended}sc(){return this.I?!0:this.O()}Oa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ya=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.u.ca(d);this.J=this.I=!1;this.Y=b;this.na=1}Fa(){const b=this.W();b.paused||b.pause();this.u.ha(b);this.I=!0;this.J=!1;this.sa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.ha(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.u.ca(this.W()),this.J=!1)}Tb(){this.W().muted=this.ya||this.Ob()}Dc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.na;this.bd&&(b*=this.u.oc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Cc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Ac(){return this.Oa()}Ec(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.u.ca(this.W()),this.va=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.He=class extends self.wd{constructor(b,a,c){super(b,a,c);this.s=null;this.ec=d=>this.Lc(d);this.Wc=!0;this.rb=null;this.S=this.hc=this.jc=0;this.gd=1}l(){this.Fa();W(this);this.ec=null;super.l()}Lc(b){this.J||this.va||b.target!==this.rb||(this.I=this.Wc=!0,this.sa=-1,W(this),Pb(this.u,"ended",this.pa,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Wc}sc(){return!this.s||this.I?!0:this.O()}Oa(){let b;b=this.J?this.S:this.hc+(V(this)-this.jc)*this.na;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.ya=!1;this.gd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ja;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.ec;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Wc=!1;this.Y=b;this.na=1;this.jc=V(this);this.hc=c}Fa(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Oa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.ec,this.s.loop=this.Y,U(this,this.Na),this.Ha(),this.s.start(0,this.S),this.jc=V(this),this.hc=this.S,this.J=!1)}zc(){return super.zc()*this.gd}Tb(){this.gd=this.ya||this.Ob()?0:1;U(this,this.Na)}Dc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.na;this.bd&&(b*=this.u.oc);this.s&&(this.s.playbackRate.value=b)}Cc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Pb()))}Ac(){return this.S}Ec(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Oa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.va=!1:this.va&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.ec,this.s.loop=this.Y,U(this,this.Na),this.Ha(),this.s.start(0,this.S),this.jc=V(this),this.hc=this.S,this.va=!1)}Kc(b){super.Kc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.ae=-1;this.T=this.md="";this.o=null}l(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.md,params:this.o}}}
self.xe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}l(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ve=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Db=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=X(this);this.vb.gain.value=c;this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Db)}l(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ib.zd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.ue=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Sd=this.Rd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.v.connect(this.ub);this.v.connect(this.h);this.ub.connect(this.i)}l(){this.v.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Rd;b.bufferUrl="";b.bufferType=this.Sd;return b}};
self.ye=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.Ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.ze=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.ib.zd;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Ce=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.De=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.Be=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Jb=X(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.v.connect(this.Jb);this.v.connect(this.h);this.Jb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.we=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=X(this);this.lc=X(this);this.kc=X(this);b=d;.01>b&&(b=.01);this.lc.gain.value=b;this.kc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.pc=this.g.createWaveShaper();this.Qc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Qc[32768+e]=f,this.Qc[32768-
e-1]=-f;this.pc.curve=this.Qc;this.v.connect(this.lc);this.v.connect(this.h);this.lc.connect(this.pc);this.pc.connect(this.kc);this.kc.connect(this.i)}l(){this.v.disconnect();this.lc.disconnect();this.pc.disconnect();this.kc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.te=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Yd=new Float32Array(this.m.frequencyBinCount);this.le=new Uint8Array(a);this.je=this.ab=0;b=this.u;b.Sa.add(this);T(b)}l(){this.u.Sa.delete(this);this.m.disconnect();super.l()}Ga(){this.m.getFloatFrequencyData(this.Yd);this.m.getByteTimeDomainData(this.le);const b=this.m.fftSize;let a=this.ab=0;for(var c=0;c<b;++c){let d=(this.le[c]-
128)/128;0>d&&(d=-d);this.ab<d&&(this.ab=d);a+=d*d}c=self.ib.Oe;this.ab=c(this.ab);this.je=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
